name: Autograding Tests
on:
  push:
    branches: [main]

permissions:
  checks: write
  actions: read
  contents: read
jobs:
  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Bril
        run: |
          bash install_bril.sh

      - name: Problem-1 - Test simple.bril
        id: problem-1
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: Test simple.bril
          command: bash ./run_test_case.sh tests/simple.bril
          max-score: 1

      - name: Problem-2 - Test loop.bril
        id: problem-2
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: Test loop.bril
          command: bash ./run_test_case.sh tests/loop.bril
          max-score: 1
      
      - name: Problem-3 - Test self_loop.bril
        id: problem-3
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: Test self_loop.bril
          command: bash ./run_test_case.sh tests/self_loop.bril
          max-score: 1

      - name: Problem-4 - Test example.bril
        id: problem-4
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: Test example.bril
          command: bash ./run_test_case.sh tests/example.bril
          max-score: 1

      - name: Problem-5 - Test while.bril
        id: problem-5
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: Test while.bril
          command: bash ./run_test_case.sh tests/while.bril
          max-score: 1

      - name: Problem-6 - Test factors.bril
        id: problem-6
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: Test factors.bril
          command: bash ./run_test_case.sh tests/factors.bril
          max-score: 1

      - name: Problem-7 - Test reverse.bril
        id: problem-7
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: Test reverse.bril
          command: bash ./run_test_case.sh tests/reverse.bril
          max-score: 1

      - name: Problem-8 - Test pascals_rows.bril
        id: problem-8
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: Test pascals_rows.bril
          command: bash ./run_test_case.sh tests/pascals_rows.bril
          max-score: 1

      - name: Autograding Reporter
        uses: classroom-resources/autograding-grading-reporter@v1
        env:
          PROBLEM-1_RESULTS: "${{ steps.problem-1.outputs.result }}"
          PROBLEM-2_RESULTS: "${{ steps.problem-2.outputs.result }}"
          PROBLEM-3_RESULTS: "${{ steps.problem-3.outputs.result }}"
          PROBLEM-4_RESULTS: "${{ steps.problem-4.outputs.result }}"
          PROBLEM-5_RESULTS: "${{ steps.problem-5.outputs.result }}"
          PROBLEM-6_RESULTS: "${{ steps.problem-6.outputs.result }}"
          PROBLEM-7_RESULTS: "${{ steps.problem-7.outputs.result }}"
          PROBLEM-8_RESULTS: "${{ steps.problem-8.outputs.result }}"
        with:
          runners: problem-1, problem-2, problem-3, problem-4, problem-5, problem-6, problem-7, problem-8
