name: build

on:
  push:
    branches:
     - main
  pull_request:
    branches:
     - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - uses: actions/setup-python@v4
        with:
            python-version: '3.11'
            cache: pip
            cache-dependency-path: bril-txt/pyproject.toml

      - name: TypeScript check
        run: deno check brili.ts brilck.ts ts2bril.ts

      - name: Install all TypeScript tools
        run: deno install brili.ts ; deno install brilck.ts ; deno install --allow-env --allow-read ts2bril.ts

      - name: Install Flit
        run: pip install flit
      - name: Install Python tools
        run: cd bril-txt ; flit install --symlink

      - name: Install Turnt
        # run: pip install turnt  # Use instead if pip turnt version >= 1.7
        uses: actions/checkout@v4
        with:
          repository: cucapra/turnt
          path: './turnt'
      - name: Install Turnt part 2
        run: cd turnt ; flit install --symlink


      - name: Problem matcher
        run: echo '::add-matcher::.github/tap-matcher.json'
      - name: Tests
        run: PATH=$PATH:`yarn global bin` make test TURNTARGS=-v

  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - uses: actions/setup-python@v4
        with:
            python-version: '3.11'
            cache: pip
            cache-dependency-path: bril-txt/pyproject.toml

      - name: Install brilck
        run: deno install brilck.ts

      - name: Install Flit
        run: pip install flit
      - name: Install Python tools
        run: cd bril-txt ; flit install --symlink

      - name: Problem matcher
        run: echo '::add-matcher::.github/brilck-matcher.json'
      - name: brilck
        run: PATH=$PATH:`yarn global bin` make check

  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: TrueBrain/actions-flake8@master
        with:
          path: bril-txt
